version: '3.8'

services:
  jupyter:
    image: jupyter/datascience-notebook:lab-4.0.2
    container_name: jupyter
    volumes:
      - ./data:/data
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=my_secret_token

#    deploy:
#        resources:
#            limits:
#              cpus: 1
#             memory: 1G